version: '3.1'

services:

  db:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123@
      POSTGRES_USER: postgres
      POSTGRES_DB: db_gerenc_proces
    ports:
      - 5432:5432


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080



